version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///cats.db
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: nouchka/sqlite3
    container_name: sqlite_db
    volumes:
      - ./cats.db:/app/cats.db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
